### ISSUE TITLE
Project discontinued?

### ISSUE THREAD

**Issue by MEESKON** [4castRenewables/climetlab-plugin-a6#3]
Hello developers,

Is this project discontinued? I am unable to pull the data when executing the example Jupyter notebook and i am not able to connect to the website. 
when executing this line:
`production_dataset = cml.load_dataset("maelstrom-power-production", wind_turbine_id = 1)`
i get:
`Recovering from connection error [HTTPSConnectionPool(host='storage.ecmwf.europeanweather.cloud', port=443): Max retries exceeded with url: [/MAELSTROM_AP6/production_data/wind_turbine_1.nc](https://file+.vscode-resource.vscode-cdn.net/MAELSTROM_AP6/production_data/wind_turbine_1.nc) (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fe009df8eb0>, 'Connection to storage.ecmwf.europeanweather.cloud timed out. (connect timeout=30)'))], attemps 1 of 500
Retrying in 120 seconds`

This data would be very valuable for writting my thesis: "_High-dimensional and resampling techniques for wind power uncertainty quantification_". 

kind regards

Mees Konijnendijk

**Comment by markusabel** [comment]
Hi Mees,
I answer for Fabian who is the main developer here.

I don't know if this project is under active maintenance. But I can tell you that we moved to gitlab with the Mantik platform, where we host as well the Maelstrom applications. It may or may not contain  the climetlab , though.

https://gitlab.com/mantik-ai

**Comment by fabian4cast** [comment]
Hey, sorry for the very late answer. The ECMWF server address changed. The changes have already been merged, but publishing currently fails. I'll fix that and release a new version soon.

But to answer your question: Yes, the project is somewhat discontinued since the MAELSTROM project has ended in March 2024, and the package was developed in the context of MAELSTROM. I'm not fully aware whether ECMWF still hosts the files that the package is supposed to provide access to, but I will soon find out.

**Comment by fabian4cast** [comment]
Version `0.2.2` has just been published to PyPI, and the downloading works as described in the README.
